name: TrafficFilter Release to NuGet

on:
  release:
    types: [published]

jobs:

  build:
  
    runs-on: ubuntu-latest
    
    steps:

    - uses: benjlevesque/short-sha@v1.2
      id: short-sha
      with:
        length: 7
        
    - run: echo $SHA

    - name: Set VER_PREFIX
      run: echo "VER_PREFIX=0.1.${{ github.run_number }}" >> $GITHUB_ENV
      
    - name: Set FileVer
      run: echo "FILE_VER=/p:FileVersion=${{ env.VER_PREFIX }}.0 /p:VersionPrefix=${{ env.VER_PREFIX }} /p:VersionSuffix=${{ env.SHA }}" >> $GITHUB_ENV
            
    - run: echo $GITHUB_RUN_NUMBER
    - run: echo ${{ github.run_number }}
    - run: echo ${{ env.VER_PREFIX }}
    - run: echo ${{ env.FILE_VER }}
        
    - name: Checkout
      uses: actions/checkout@v4
      continue-on-error: false

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
      continue-on-error: false
        
    - name: Restore
      run: dotnet restore
      continue-on-error: false

    - name: Build
      run: dotnet build --configuration Release --no-restore
      continue-on-error: false
      
    - name: Test
      run: dotnet test --no-restore
      continue-on-error: false

    - name: Pack nugets
      run: dotnet pack -c Release --no-build --output .

    - name: Push to NuGet
      run: dotnet nuget push "*.nupkg" --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json

